import tkinter as tk
import random as ran
import tkinter.messagebox 
import os


win = tk.Tk()


win.title('網頁app製作器')
win.geometry('450x350')
win.configure(bg='#363940')
headtext_font="微軟正黑體 16"
text_font="微軟正黑體 12"



def ok():
    url = (url_entry.get())
    name = str(name_entry.get())
    if url != "" and name != "":
        url = (url_entry.get())
        name = str(name_entry.get())
        name = str(name)+".py"
        url = '("'+str(url)+'")'
        print(url)
        folder=(str(os.path.dirname(__file__))+"\web")
        folder=folder.replace("\\", "\\\\")
        randomname = ran.randint(0,1000)
        htmlfilename = (str(os.path.dirname(__file__))+"\web\\"+str(randomname)+".html")
        htmlfilename = htmlfilename.replace("\\", "\\\\")
        htmlfile=open(htmlfilename, mode="w")
        data='''
<!DOCTYPE html>
<html>
<body>
<script>
    // Javascript URL redirection - generated by www.rapidtables.com
    window.location.replace'''+str(url)+''';
</script>
</body>
</html>'''
        htmlfile.write(data)


        pythonfile=open(str(name), mode="w")
        pydata='''import eel
eel.init("'''+str(folder)+'''")
eel.start("'''+str(htmlfilename)+'''",size=(320,200))
'''
        pythonfile.write(pydata)

        wrong=str(name)+"創建成功!!"
        wrong_label.configure(fg="green",text=wrong)



    else:
        tkinter.messagebox.showerror('錯誤','名稱或網址未填')




header_label = tk.Label(win,bg="#363940",fg="white",text='網頁APP製作器',font=headtext_font)
header_label.pack(side=tk.TOP)



wrong_label = tk.Label(win,bg="#363940",fg="green",text='',font="微軟正黑體 12")
wrong_label.pack(side=tk.TOP)

token_frame=tk.Frame(win)
token_frame.pack(side=tk.TOP)
word = tk.Label(win,bg="#363940",fg="white",text="名稱:",font=text_font)
word.pack(side=tk.TOP)
name_entry=tk.Entry(win,bg="white",fg="black",font=text_font)
name_entry.pack(side=tk.TOP)

word = tk.Label(win,bg="#363940",fg="white",text=" ",font=text_font)
word.pack(side=tk.TOP)

token_frame=tk.Frame(win)
token_frame.pack(side=tk.TOP)
word = tk.Label(win,bg="#363940",fg="white",text="網址:",font=text_font)
word.pack(side=tk.TOP)
url_entry=tk.Entry(win,bg="white",fg="black",font=text_font)
url_entry.pack(side=tk.TOP)

word = tk.Label(win,bg="#363940",fg="white",text=" ",font=text_font)
word.pack(side=tk.TOP)


ok_btn = tk.Button(win,bg="#363940",fg="white",text='  OK  ',font=text_font,command=ok)
ok_btn.pack(side=tk.TOP)

word = tk.Label(win,bg="#363940",fg="white",text="  \n   ",font=text_font)
word.pack(side=tk.TOP)

word = tk.Label(win,bg="#363940",fg="red",text="注意:如網頁無法顯示，請檢查網址是否有誤",font=text_font)
word.pack(side=tk.TOP)

win.mainloop()